(()=>{'use strict';
const $=id=>document.getElementById(id),months=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'],week=['ش','ی','د','س','چ','پ','ج'];
const fmt=new Intl.DateTimeFormat('en-US-u-ca-persian-nu-latn',{year:'numeric',month:'numeric',day:'numeric'});
const parts=d=>{const p=fmt.formatToParts(d),o={};p.forEach(x=>{if(['year','month','day'].includes(x.type))o[x.type]=Number(x.value)});return o};
const fa=n=>new Intl.NumberFormat('fa-IR').format(n),pad=n=>String(n).padStart(2,'0');
const iso=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const fromIso=s=>{if(!s)return null;const a=s.split('-').map(Number);return a.length===3?new Date(a[0],a[1]-1,a[2],12):null};
const start=y=>{for(let day=18;day<=24;day++){const d=new Date(y+621,2,day,12),p=parts(d);if(p.year===y&&p.month===1&&p.day===1)return d}return new Date(y+621,2,20,12)};
const monthStart=(y,m)=>{const d=start(y);d.setDate(d.getDate()+(m<=6?(m-1)*31:186+(m-7)*30));return d};
const toIso=(y,m,d)=>{if(y<1200||m<1||m>12||d<1||d>31)return '';const first=monthStart(y,m),next=m===12?start(y+1):monthStart(y,m+1),max=Math.round((next-first)/86400000);if(d>max)return '';first.setDate(first.getDate()+d-1);return iso(first)};
const fromGregorian=s=>{const d=fromIso(s);if(!d)return '';const p=parts(d);return fa(p.year)+'/'+fa(p.month).padStart(2,'۰')+'/'+fa(p.day).padStart(2,'۰')};
let active=null,view={year:1405,month:1};
const popup=document.createElement('div');popup.className='jalali-overlay';popup.hidden=true;popup.innerHTML='<section class="jalali-dialog" role="dialog" aria-modal="true" aria-label="انتخاب تاریخ شمسی"><header class="jalali-head"><button type="button" data-move="-1" aria-label="ماه قبل">‹</button><strong id="jp-title"></strong><button type="button" data-move="1" aria-label="ماه بعد">›</button></header><div class="jalali-week">'+week.map(x=>'<span>'+x+'</span>').join('')+'</div><div class="jalali-days" id="jp-days"></div><footer class="jalali-foot"><button type="button" class="btn" id="jp-clear">پاک‌کردن</button><button type="button" class="btn primary" id="jp-today">امروز</button></footer></section>';document.body.appendChild(popup);
function draw(){const title=$('jp-title'),grid=$('jp-days');title.textContent=months[view.month-1]+' '+fa(view.year);const first=monthStart(view.year,view.month),offset=(first.getDay()+1)%7,next=view.month===12?start(view.year+1):monthStart(view.year,view.month+1),count=Math.round((next-first)/86400000),selected=active&&$(active.dataset.jalaliTarget).value;let html='';for(let i=0;i<offset;i++)html+='<span class="jp-blank"></span>';for(let day=1;day<=count;day++){const value=toIso(view.year,view.month,day);html+='<button type="button" class="jp-day'+(value===selected?' selected':'')+'" data-date="'+value+'">'+fa(day)+'</button>'}grid.innerHTML=html}
function open(input){active=input;const target=$(input.dataset.jalaliTarget),p=parts(fromIso(target.value)||new Date());view={year:p.year,month:p.month};draw();popup.hidden=false;document.body.classList.add('jalali-open')}
function close(){popup.hidden=true;document.body.classList.remove('jalali-open');active=null}
window.setJalaliPickerValue=(id,value)=>{const input=document.querySelector('[data-jalali-target="'+id+'"]');if(input)input.value=fromGregorian(value)};
document.querySelectorAll('[data-jalali-target]').forEach(input=>{input.readOnly=true;input.autocomplete='off';input.addEventListener('click',()=>open(input));input.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(input)}});const target=$(input.dataset.jalaliTarget);if(target&&target.value)input.value=fromGregorian(target.value)});
popup.addEventListener('click',e=>{if(e.target===popup){close();return}const move=e.target.closest('[data-move]');if(move){view.month+=Number(move.dataset.move);if(view.month<1){view.month=12;view.year--}if(view.month>12){view.month=1;view.year++}draw();return}const day=e.target.closest('[data-date]');if(day&&active){const target=$(active.dataset.jalaliTarget);target.value=day.dataset.date;active.value=fromGregorian(day.dataset.date);target.dispatchEvent(new Event('change',{bubbles:true}));close();return}if(e.target.id==='jp-clear'&&active){const target=$(active.dataset.jalaliTarget);target.value='';active.value='';target.dispatchEvent(new Event('change',{bubbles:true}));close();return}if(e.target.id==='jp-today'&&active){const target=$(active.dataset.jalaliTarget),now=iso(new Date());target.value=now;active.value=fromGregorian(now);target.dispatchEvent(new Event('change',{bubbles:true}));close()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!popup.hidden)close()});
})();